"use client";

interface LowStockItem {
  id: string;
  name: string;
  sku: string;
  stock: number;
  min: number;
}

export default function LowStockClient({ items }: { items: LowStockItem[] }) {
  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Low Stock Report - City Shop Centre</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #111; }
          h1 { text-align: center; font-size: 28px; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 2px; }
          .subtitle { text-align: center; font-size: 14px; color: #666; margin-bottom: 30px; }
          .date { text-align: right; font-size: 13px; color: #888; margin-bottom: 20px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          th { background: #f3f4f6; padding: 12px 16px; text-align: left; font-weight: 700; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #e5e7eb; }
          td { padding: 12px 16px; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
          .critical { color: #dc2626; font-weight: 800; }
          .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #999; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>City Shop Centre</h1>
        <p class="subtitle">Purchase Order - Low Stock Items</p>
        <p class="date">Date: ${new Date().toLocaleDateString()} | Time: ${new Date().toLocaleTimeString()}</p>
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Product Name</th>
              <th>SKU</th>
              <th>Current Stock</th>
              <th>Min Required</th>
              <th>Order Qty (Suggested)</th>
            </tr>
          </thead>
          <tbody>
            ${items.map((item, i) => `
              <tr>
                <td>${i + 1}</td>
                <td><strong>${item.name}</strong></td>
                <td>${item.sku}</td>
                <td class="critical">${item.stock}</td>
                <td>${item.min}</td>
                <td><strong>${Math.max(item.min * 2 - item.stock, item.min)}</strong></td>
              </tr>
            `).join("")}
          </tbody>
        </table>
        <p class="footer">Generated by City Shop Centre POS System</p>
        <script>window.onload = () => { window.print(); }</script>
      </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
  };

  return (
    <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden flex flex-col h-full relative">
      <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-red-400 to-rose-600"></div>
      <div className="px-4 py-3 border-b border-gray-100">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 bg-red-100 rounded-lg flex items-center justify-center text-base shadow-inner text-red-600 border border-red-200/50">🚨</div>
          <div>
            <h3 className="text-sm font-bold text-gray-900">Critical Alerts</h3>
            <p className="text-[11px] font-medium text-gray-500">Requires restocking</p>
          </div>
        </div>
      </div>
      
      <div className="p-3 space-y-2 flex-1 bg-gray-50/20">
        {items.length > 0 ? (
          items.map((item) => (
            <div key={item.id} className="group flex items-center justify-between p-3 rounded-lg border border-red-100/60 bg-white hover:bg-red-50/30 transition-all duration-300 shadow-sm hover:shadow-md hover:border-red-200">
              <div className="flex-1 min-w-0 pr-3">
                <p className="font-extrabold text-gray-900 text-sm truncate group-hover:text-red-700 transition-colors">{item.name}</p>
                <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold bg-gray-100 text-gray-600 mt-0.5">SKU: {item.sku}</span>
              </div>
              <div className="text-right flex-shrink-0">
                <div className="bg-red-50 px-2 py-1 rounded-md border border-red-100 inline-block text-center min-w-[50px]">
                  <p className="text-lg font-black text-red-600 leading-none">{item.stock}</p>
                  <p className="text-[8px] font-bold text-red-500 uppercase tracking-wider mt-0.5">LEFT</p>
                </div>
                <p className="text-[10px] font-bold text-gray-400 mt-0.5 text-center">Min: {item.min}</p>
              </div>
            </div>
          ))
        ) : (
          <div className="text-center py-8">
            <div className="w-14 h-14 bg-green-50 rounded-full flex items-center justify-center text-2xl mx-auto mb-2 border border-green-100">✅</div>
            <p className="font-bold text-gray-900 text-sm">Inventory looks perfect</p>
            <p className="text-[11px] font-medium text-gray-500 mt-0.5">No alerts.</p>
          </div>
        )}
      </div>
      
      {items.length > 0 && (
        <div className="p-3 border-t border-gray-100 bg-white">
          <button
            onClick={handlePrint}
            className="w-full py-2.5 bg-gray-900 text-white rounded-lg text-xs font-bold hover:bg-black transition-colors shadow-md hover:shadow-lg flex items-center justify-center gap-2"
          >
            <span>🖨️</span> Generate PO & Print
          </button>
        </div>
      )}
    </div>
  );
}
